### ISSUE TITLE
Management UI: The policy page displays : error getting policy data

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/icap-management-ui#114] opened 2021-01-04 14:18 UTC
To replicate:
Go to http://management-ui.northeurope.cloudapp.azure.com
Go to Policy
![2021-01-04_14h17_00.png](https://images.zenhubusercontent.com/5f315efe0e4f4158677aea6e/1c933e22-9b9c-4203-ad3b-61aacda465ca)

**Comment by mpigram** [comment] 2021-01-04 14:21
@gw-sbirch are you able to take a look please? If you need any help from me let me know. This was the same issue Nadege was having before xmas break also.

**Comment by gw-sbirch** [comment] 2021-01-04 15:22
@mpigram

The service is complaining because of the new configuration option. This should be fixed when develop is merged into main I believe.

A work around might be to add the two options in develop that are not in main.

**Comment by gw-sbirch** [comment] 2021-01-04 15:25
I have done this, but the config will reset if it is redeployed

**Comment by mpigram** [comment] 2021-01-04 15:31
Nice one @gw-sbirch - we shouldn't need to be redeploying at this moment. Me and Paul are working on merging dev with main soon, so that should solve this issue.

Did those config changes take long? If not I may get you to do it again if we redeploy

**Comment by mpigram** [comment] 2021-01-04 15:32
@NadHodeGW can confirm that policies are now appearing and no longer receiving the error, thanks to @gw-sbirch

**Comment by gw-sbirch** [comment] 2021-01-04 15:34
@mpigram dont take long, I just added these to the policy API deployment:
```

- name: PolicyUpdateServiceUsername
            valueFrom:
              secretKeyRef:
                key: TokenUsername
                name: policyupdateserviceref
          - name: NcfsPolicyUpdateServiceUsername
            valueFrom:
              secretKeyRef:
                key: TokenUsername
                name: policyupdateserviceref
          - name: PolicyUpdateServicePassword
            valueFrom:
              secretKeyRef:
                key: TokenPassword
                name: policyupdateserviceref
          - name: NcfsPolicyUpdateServicePassword
            valueFrom:
              secretKeyRef:
                key: TokenPassword
                name: policyupdateserviceref
```

**Comment by NadHodeGW** [comment] 2021-01-04 16:16
@gw-sbirch, thank you.
policies flags are displayed but not the History. Can you have a look please.
![2021-01-04_16h13_28](https://user-images.githubusercontent.com/61200359/103555403-1fce0600-4ea8-11eb-8757-7a15847ee2f8.png)

**Comment by gw-sbirch** [comment] 2021-01-04 17:48
@NadHodeGW  @mpigram 

After further inspection, although the service is starting, no policies are being found because the work to mount the azure file store is also needed to be merged to main. So I dont think theres a work around until dev is merged into main

**Comment by NadHodeGW** [comment] 2021-01-07 09:13
@gw-sbirch 
This is the same issue on UK south & East US 
Policy and Request History can't be accessed

**Comment by gw-sbirch** [comment] 2021-01-11 14:42
@NadHodeGW this is now working at http://management-ui-qa.uksouth.cloudapp.azure.com/request-history

**Comment by asloman** [comment] 2021-01-11 16:53
Checked on uk south qa, east us, north europe.

Policy page is displaying correctly as expected.

Reproduction steps:
Go to http://management-ui.northeurope.cloudapp.azure.com
Go to Policy

Expected Results: Able to see policy pages

Actual Results: Able to see policy pages

**Closed** 2021-05-13 13:22 UTC
Labels: P1, bug
